MyBookRecord/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('record.urls')),
    path('admin/', admin.site.urls),
]

record/urls.py
from django.urls import path
from . import views

app_name = 'record'
urlpatterns = [
     path('', views.base, name='base'),
     path('<int:book_id>/book_detail', views.book_detail, name='book_detail'),
     path('bookshelf/', views.bookshelf, name='bookshelf'),
     path('data/', views.data, name='data'),
     path('profile/', views.profile, name='profile'),
     path('recommend/', views.recommend, name='recommend'),
     path('webhook/', views.webhook, name='webhook'),
]

record/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.timezone import now

# Create your models here.

class Book(models.Model):
    title = models.CharField("本のタイトル", max_length=50)
    author = models.CharField("筆者の名前", max_length=20)
    image = models.ImageField("表紙")
    register_day = models.DateTimeField(verbose_name="登録日時", auto_now_add=True, null=True)


class Likephrase(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    page = models.IntegerField("ページ数", null=True)
    like_phrase = models.TextField("好きなフレーズ", null=True)
    comment = models.TextField('コメント', null=True)

record/views.py
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from record.models import Book, Likephrase
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core import serializers
from datetime import datetime, timedelta
import json
import requests
import sys
import os
from . import models
import collections
import logging


# Create your views here.

def base(request):

    books = Book.objects.order_by('-register_day')
    paginator = Paginator(books, per_page=3)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)

    except (EmptyPage, PageNotAnInteger):
        books = paginator.page(1)

    return TemplateResponse(request, 'record/base.html',
                            {'books': books,
                             })


# 本の詳細画面
def book_detail(request, book_id):
    books = Book.objects.filter(id=book_id)
    ph = Likephrase.objects.filter(book_id=book_id)
    book_page = Likephrase.objects.values('page').filter(book_id=book_id)

    return TemplateResponse(request, 'record/book_detail.html',
                                     {'books': books,
                                      'phrase': ph,
                                      'book_page': book_page })


def bookshelf(request):

    books = Book.objects.order_by('-register_day')
    paginator = Paginator(books, per_page=9)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)

    except (EmptyPage, PageNotAnInteger):
        books = paginator.page(1)

    return TemplateResponse(request, 'record/bookshelf.html',
                              {'books': books,
                                })


def data(request):
    month = 1
    book_total = 0
    book_count = [0,0,0,0,0,0,0,0,0,0,0,0]


    this_month = datetime.today().month
    last_month = this_month - 1
    while month <= this_month:
        count = Book.objects.filter(register_day__month = month).count()
        book_count[month -1] = count
        book_total += count
        month += 1

    this_month = book_count[this_month - 1]
    last_month = book_count[last_month - 1]

    return TemplateResponse(request, 'record/data.html',
                             {'book_count': book_count,
                              'book_total': book_total,
                              'this_month': this_month,
                              'last_month': last_month})


def profile(request):
    return TemplateResponse(request, 'record/profile.html')


def recommend(request):
    return TemplateResponse(request, 'record/recommend.html')


@csrf_exempt
def webhook(request):
    req = json.loads(request.body)
    # intent_name = req.get('queryResult').get('intent').get('displayName')
    intent_name = req.get('queryResult').get('intent').get('displayName')
    text = req.get('queryResult').get('queryText')
    session_id = req['session']
    list = []

    if intent_name == "Registration":
        fulfillmentMessages = Start()
        return JsonResponse(fulfillmentMessages)

# 　タイトルを入力してコンテキストの情報を取得する
    if intent_name == 'Registration - ChoiceResponse - TitleResponse':
        outputContext = req.get('queryResult').get('outputContexts')[-2]
        context_text = outputContext.get('parameters').get('Process')

        if context_text == None:
            fulfillmentText = {"fulfillmentText": "異常が発生しました"}
            return JsonResponse(fulfillmentText)


# 　コンテキストの名前が登録ならAPIを呼び出して、その情報を元に登録したい本に間違いないか確認
        if context_text == "本棚に追加":

            list = RakutenAPI(request)
            if type(list) == str:

                fulfillmentMessages = {"fulfillmentMessages": [
                        {
                            "payload":
                            {
                                "line": {
                                    "type": "template",
                                    "altText": "test_template",
                                    "template": {
                                        "type": "buttons",
                                        'title': "ERROR!!",
                                        "text": list,
                                        "thumbnailImageUrl" : 'https://cdn.pixabay.com/photo/2016/04/24/13/24/error-1349562__340.png',
                                        "actions": [
                                            {
                                                "type": "message",
                                                "label": "はい",
                                                "text": "はい"
                                            }
                                        ]
                                    }
                                }
                            }
                        }
                    ]
                    }

                return JsonResponse(fulfillmentMessages)

# __system_counters__がいつのまにか増えているとしたら全部1マイナスを増やしてみる

            else:
                fulfillmentMessages = ConfirmBook(list)
                return JsonResponse(fulfillmentMessages)

#  APIで本の情報を取得後、YESならその情報を元にデータ作成(登録の最終ステップ)
    if text == "YES":
        outputContext = req.get('queryResult').get('outputContexts')[-2]
        outputContext_2 = req.get('queryResult').get('outputContexts')[-3]
        context_text = outputContext.get('parameters').get('Process')
        context_text_2 = outputContext_2.get('parameters').get('Process')
        context_title = outputContext.get('parameters').get('any')

        if context_text == "本棚に追加":
            if intent_name == "Registration - ChoiceResponse - TitleResponse - YesResponse":

                list = RakutenAPI(request)
                title = list[0]
                author = list[1]
                image = list[2]
                msg = CheckBook(title)

                if msg == "":
                    book = Book.objects.create(title=title, author=author, image=image)
                    fulfillmentText = {"fulfillmentText": "登録が完了しました"}
                    return JsonResponse(fulfillmentText)
                else:
                    fulfillmentText = {"fulfillmentText": "すでに" + title + "が登録されています"}
                    return JsonResponse(fulfillmentText)

            elif intent_name == "Registration - ChoiceResponse - TitleResponse - NoResponse - AuthorResponse - YesResponse":
                list = RakutenAPI(request)
                title = list[0]
                author = list[1]
                image = list[2]
                msg = CheckBook(list)

                if msg == "":
                    book = Book.objects.create(title=title, author=author, image=image)
                    fulfillmentText = {"fulfillmentText": "登録が完了しました"}
                    return JsonResponse(fulfillmentText)
                else:
                    fulfillmentText = {"fulfillmentText": "すでに" + title + "は登録されています"}
                    return JsonResponse(fulfillmentText)

        elif context_text_2 == "本棚から削除":
            outputContext = req.get('queryResult').get('outputContexts')[-2]
            title = outputContext.get('parameters').get('any')
            Book.objects.filter(title__icontains=title).delete()
            fulfillmentText = {"fulfillmentText": "削除が完了しました"}
            return JsonResponse(fulfillmentText)

# 　タイトルだけでは商品情報が取得できずに著者名を入力する場合
    if intent_name == "Registration - ChoiceResponse - TitleResponse - NoResponse - AuthorResponse":
        outputContext = req.get('queryResult').get('outputContexts')[-2]
        author = outputContext.get('parameters').get('person').get('name')
        list = RakutenAPI(request)
        fulfillmentMessages = ConfirmBook(list)
        return JsonResponse(fulfillmentMessages)



# 　入力したタイトルの情報を取得する(すでに登録済みの本情報)
    if intent_name == 'Registration - AddResponse - Title' or intent_name == "Registration - DeleteResponse - TitleResponse":
        text = req.get('queryResult').get('queryText')
        global book_title
        book_title = text

        search_books = SearchBook(book_title)
        if search_books == "":
            data = collections.OrderedDict()
            data['fulfillmentText'] = "本棚に存在しません"
            data['outputContexts'] = [
            collections.OrderedDict([
                ('name', session_id + '/contexts/registration-addresponse-title-followup'),
                ('lifespanCount', 0)
            ]),
            collections.OrderedDict([
                ('name', session_id + '/contexts/registration-addresponse-followup'),
                ('lifespanCount', 0)
            ]),
    ]
            return JsonResponse(data)

        else:
            list.append(search_books[1])
            list.append(search_books[2])
            list.append(search_books[3])
            fulfillmentMessages = ConfirmBook(list)
            return JsonResponse(fulfillmentMessages)


# 　好きなフレーズを入力する
    if intent_name == 'Registration - AddResponse - Title - Yes - Page - Phrase':
        outputContext = req.get('queryResult').get('outputContexts')[1]
        judge = outputContext.get('parameters').get('Judge')
        number = outputContext.get('parameters').get('number')
        pk = SearchBook(book_title)
        pk = pk[0]
        text = req.get('queryResult').get('queryText')
        book = get_object_or_404(models.Book, id = pk)
        Likephrase.objects.create(book=book, like_phrase=text, page=number)
        data = collections.OrderedDict()

        data["fulfillmentMessages"] = [
                    {
                      "card": {
                            "title": "登録が完了しました",
                            "subtitle": "続いて好きなフレーズを登録しますか？",
                            "imageUri": 'https://cdn.pixabay.com/photo/2016/06/01/06/26/open-book-1428428__340.jpg',
                            "buttons": [
                                {
                                    "text": "YES",

record/templates/record/base.html
{% load static %}

<!DOCTYPE html>
  <html lang="ja">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1.0 ,user-scalable=no,minimum-scale=1.0">
    <title>{% block title %}My Book Record{% endblock %}</title>
  </head>

  <body>
    <!-- ここからデータベースに入っているものをループして取り出す -->
    <div class="wrappers">
      <header>
        <div class="header-image">
          <a href="{% url 'record:base' %}"></a>
        </div>
        <nav>
          <ul class="header-nav">
            <li><a href="{% url 'record:bookshelf' %}">本棚</a></li>
            <li><a href="{% url 'record:recommend' %}">ランキング</a></li>
            <li><a href="{% url 'record:data' %}">読書データ</a></li>
            <li><a href="{% url 'record:profile' %}">プロフィール</a></li>
          </ul>
        </nav>
      </header>
{% block content %}
      <div class="contents-wrapper">
{% if books %}
{% for book in books %}
     <div class="content-list"><a href="{% url 'record:book_detail' book_id=book.id%}">
        <div class="content-image">
          <p><img src="{{ book.image }}"></p>
        </div>
        <div class="content-texts">
          <div class="content-text">
          <h1 class="text">タイトル</h1>
          <p class="text">{{ book.title }}</p>
          </div>
          <div class="content-text">
          <h1 class="text">著者</h1>
          <p class="text">{{ book.author }}</p>
          </div>
          <div class="content-text">
          <h1 class="text">登録完了日</h1>
          <p class="text">{{ book.register_day }}</p>
          </div>
        </div>
    </div>
    </a>
{% endfor %}
{% endif %}
      </div>
      <div class="paginator">
        {% if books.has_previous %}
        <a href="?page={{ books.previous_page_number }}">&lt; 前のページ</a>
        {% else %}
        <span>&lt; 前のページ</span>
        {% endif %}

        <span class="current-page">{{ books.number }}</span>

        {% if books.has_next %}
        <a href="?page={{ books.next_page_number }}">次のページ &gt;</a>
        {% else %}
        <span>次のページ &gt;</span>
        {% endif %}
      </div>
      </div>
{% endblock %}
    <!-- ここまで複数個あり -->
    <!-- ページネーションの必要あり -->
  </body>

  </html>

record/templates/record/book_detail.html
{% extends 'record/base.html' %}
{% load static %}
{% block title %} 詳細ページ {% endblock %}

{% block content %}

<div class="contents-wrapper">
  {% for book in books %}
  <div class="content-list">
    <div class="content-image">
      <p><img src="{{ book.image }}" </p> </div> <div class="content-texts">
        <div class="content-text">
          <h1 class="text">タイトル</h1>
          <p class="text">{{ book.title }}</p>
        </div>
        <div class="content-text">
          <h1 class="text">著者</h1>
          <p class="text">{{ book.author }}</p>
        </div>
        <div class="content-text">
          <h1 class="text">読書完了日</h1>
          <p class="text">{{ book.register_day }}</p>
        </div>
    </div>
    {% endfor %}
  </div>

</div>
<div class="detail-wrapper">
  <div class="like-phrase">
    <h1>気に入った文章</h1>
    <br>
  </div>

    {% for ph in phrase %}
      <div class="phrase_text">
        <span class="phrase_page">P{{ ph.page }}</span>
        {{ ph.like_phrase }}
      </div>
    {% empty %}
      <div class="nothing_phrase">
        <p>好きなフレーズが登録されていません</p>
      </div>
    {% endfor %}

</div>


{% endblock %}

</div>
</body>

</html>

record/templates/record/bookshelf.html
{% extends 'record/base.html' %}
{% load static %}
{% block title %} 本棚 {% endblock %}

{% block content %}


      <div class="contents-wrapper bookshelf-wrapper">
        {% for book in books %}
        <div class="content-image bookshelf-image">
          <a href="{% url 'record:book_detail' book_id=book.id %}"><img src="{{ book.image }}"></a>
        </div>
        {% endfor %}
      </div>


      <div class="paginator">
         {% if books.has_previous %}
         <a href="?page={{ books.previous_page_number }}">&lt; 前のページ</a>
         {% else %}
         <span>&lt; 前のページ</span>
         {% endif %}

         <span class="current-page">{{ books.number }}</span>

         {% if books.has_next %}
         <a href="?page={{ books.next_page_number }}">次のページ &gt;</a>
         {% else %}
         <span>次のページ &gt;</span>
         {% endif %}
       </div>

{% endblock %}
</div>

  </body>

  </html>

record/templates/record/data.html
{% extends 'record/base.html' %}
{% load static %}
{% block title %} 読書データ {% endblock %}

{% block content %}

     <div class="book-data">
       <h1 class="book_title">読書データ</h1>
       <canvas id="MyChart" style="position: relative; width="220" height="220"></canvas>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
       <script>
         var ctx = document.getElementById("MyChart");
         Chart.defaults.global.defaultFontColor = 'white';
         var myBarChart = new Chart(ctx, {
           type: 'bar',
           data: {
             labels: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
             datasets: [
               {
                 label: '月ごとの読書数',
                 data: [{{book_count.0}}, {{book_count.1}}, {{book_count.2}}, {{book_count.3}}, {{book_count.4}}, {{book_count.5}}, {{book_count.6}}, {{book_count.7}}, {{book_count.8}}, {{book_count.9}}, {{book_count.10}}, {{book_count.11}}],
                 backgroundColor: "rgba(255,255,255,0.8)"
               }
             ]
           },
           options: {
             scales: {
               yAxes: [{
                 ticks: {
                   suggestedMax: 30,
                   suggestedMin: 0,
                   stepSize: 5,
                   callback: function(value, index, values){
                     return  value +  '冊'
                   }
                 }
               }]
             },
           }
         });
       </script>
     </div>
     <div class="book_info">
       <p>今月の読書冊数 ⇒  <span>{{ this_month }}冊</span></p>
       <br>
       <p>先月の読書冊数 ⇒  <span>{{ last_month }}冊</span></p>
       <br>
       <p>合計冊数 ⇒  <span>{{ book_total }}冊</span></p>
       <br>
    </div>

{% endblock %}
    </div>
    <!-- ここまで複数個あり -->
    <!-- ページネーションの必要あり -->
  </body>

  </html>

record/templates/record/profile.html
{% extends 'record/base.html' %}
{% load static %}
{% block title %} プロフィール {% endblock %}

{% block content %}

      <div class="profile">
        <div class="profile-img">
          <div class="pc_prof1">
            <img src="/static/img/pc_prof1.png" alt="aaa">
          </div>
          <div class="iphone_prof1">
            <img src="/static/img/iphone_prof2.png" alt="aaa">
          </div>
        </div>
        <div class="profile-text">
          <div class="profile-list">
            <h1>名前</h1>
            <p>nozomi</p>
          </div>
          <div class="profile-list">
            <h1>年齢</h1>
            <p>25歳</p>
          </div>

          <div class="profile-list">
            <h1>趣味</h1>
            <p>映画鑑賞、読書、プログラミング</p>
          </div>
        </div>
      </div>
      <br>
      <div class="clear">
      </div>
      <div class="introduction">
        <div class="introduction-title">
        <h1>自己紹介</h1>
        </div>
        <blockquote>
        <p>
            nozomiと言います!!<br>
            伊坂幸太郎さんの「砂漠」という小説を読んでから読書が好きになりました。<br>
            小説にとどまらずビジネス書や自己啓発のような本何でも読みます。<br>
            いまだに本は紙で購入派で、本棚に並べたいタイプです😎<br>
        </p>
        </blockquote>

      </div>
      <div class="other-app">
        <h1>MyBookRecord を作った経緯</h1>
        <blockquote>
        <p>大学生の頃、ゼミの教授に　「人の書いた文章をマネするだけでも文章力が上がる」<br>
        と本当か嘘かわからないことを言われ、読んだ本の中で好きなフレーズをエクセルに書き残していました。<br>
        <br>
        社会人になってからITの会社で働くことになり、プログラミングに興味を持ち独学で勉強開始<br>
        少しずつサイトを作れるようになってきて「エクセルに書くのではなく公開できるサイトを作ろう！」<br>
        と思い、作成することにしました😆</p>
        </blockquote>
      </div>
{% endblock %}
    </div>
    <!-- ここまで複数個あり -->
    <!-- ページネーションの必要あり -->
  </body>

  </html>

record/templates/record/recommend.html
{% extends 'record/base.html' %}
{% load static %}
{% block title %} オススメランキング {% endblock %}

{% block content %}

      <div class="recommend">
        <div class="recommend-title">
          <h1>夏休みに読みたい本 Best3</h1>
        </div>
        <div class="recommend-wrapper">
        <label>1位</label>
        <div class="recommend-wrap">
          <div class="recommend-image">
            <p>写真の予定</p>
          </div>
          <div class="recommend-text">
            <p>オススメ本を紹介予定</p>
          </div>
        </div>
        <label>2位</label>
        <div class="recommend-wrap">
          <div class="recommend-image">
            <p>写真の予定</p>
          </div>
          <div class="recommend-text">
            <p>オススメ本を紹介予定</p>
          </div>
        </div>
        <label>3位</label>
        <div class="recommend-wrap">
          <div class="recommend-image">
            <p>写真の予定</p>
          </div>
          <div class="recommend-text">
            <p>オススメ本を紹介予定</p>
          </div>
        </div>
      </div>
      <br>
    </div>
{% endblock %}
    </div>
    <!-- ページネーションの必要あり -->
  </body>

  </html>